## General
[[param]]
name = "network"
type = "String"
## bitcoin, signet
default = "\"signet\".into()"
doc = "The cryptocurrency network to act on"

## Wallet configurations

[[param]]
name = "receive_descriptor"
type = "String"
default = "\"tr([7d94197e/86'/1'/0']tpubDCyQVJj8KzjiQsFjmb3KwECVXPvMwvAxxZGCP9XmWSopmjW3bCV3wD7TgxrUhiGSueDS1MU5X1Vb1YjYcp8jitXc5fXfdC1z68hDDEyKRNr/0/*)\".into()"
doc = "The wallet descriptor used to receive funds"

[[param]]
name = "change_descriptor"
type = "String"
default = "\"tr([7d94197e/86'/1'/0']tpubDCyQVJj8KzjiQsFjmb3KwECVXPvMwvAxxZGCP9XmWSopmjW3bCV3wD7TgxrUhiGSueDS1MU5X1Vb1YjYcp8jitXc5fXfdC1z68hDDEyKRNr/1/*)\".into()"
doc = "The wallet descriptor used to receive change"

[[param]]
name = "lookahead"
type = "u32"
default = "30"
doc = "The number of scripts to peek ahead when scanning for transactions"

[[param]]
name = "height"
type = "u32"
optional = true
doc = "Begin searching for transactions strictly after the specified height"

## Node configurations

[[param]]
name = "peers"
type = "u8"
default = "2"
doc = "Number of peers to connect to"
